main: OTU2MDQ5OTEyNjk5NzE1NjM0.GPtpxr.ytluRPxD1D_Nb8TFyoY5Cn_ACsV7rDAVe5tRuA
dev: OTU3NjIxNTcwMTI4NDQ5NjI2.GwNWCW.43z2_mO8EyEHnrL-jZpG-knYSvcFjCnrFUXCAY
lavalink: EGUD4w69vQdtBK
ltuid: 7368957
ltoken: X5VJAbNxdKpMp96s7VGpyIBhSnEJr556d5fFMcT5